name: Deploy to EC2 from DockerHub

on:
  push:
    branches:
      - QA
  pull_request:
    branches:
      - main

env:
  DOCKER_REPOSITORY: ztencontacto/myapp
  QA_APP_PORT: 4568
  PROD_APP_PORT: 4568

jobs:
  # Job 1: Construcción y publicación en DockerHub
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [QA, PROD]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image for ${{ matrix.environment }}..."
          docker build -t ${{ env.DOCKER_REPOSITORY }}:${{ matrix.environment | toLowerCase }} .
          echo "Pushing Docker image to DockerHub..."
          docker push ${{ env.DOCKER_REPOSITORY }}:${{ matrix.environment | toLowerCase }}
          echo "Docker image built and pushed successfully for ${{ matrix.environment }}."

  # Job 2: Despliegue en QA
  deploy-to-qa:
    needs: build-and-push
    if: github.ref == 'refs/heads/QA'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy QA Image to EC2
        run: |
          echo "Deploying QA Docker image to EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_KEY_QA }}") ubuntu@${{ secrets.EC2_HOST_QA }} "
            if ! command -v docker &> /dev/null; then
              sudo apt update && sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi
            echo 'Pulling QA Docker image...'
            sudo docker pull ${{ env.DOCKER_REPOSITORY }}:qa
            echo 'Stopping and removing existing container...'
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            echo 'Running new container...'
            sudo docker run -d --name myapp -p ${{ env.QA_APP_PORT }}:${{ env.QA_APP_PORT }} ${{ env.DOCKER_REPOSITORY }}:qa
          "
          echo "QA Docker image deployed successfully."

  # Job 3: Despliegue en Producción
  deploy-to-prod:
    needs: build-and-push
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production Image to EC2
        run: |
          echo "Deploying Production Docker image to EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_KEY_PROD }}") ubuntu@${{ secrets.EC2_HOST_PROD }} "
            if ! command -v docker &> /dev/null; then
              sudo apt update && sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi
            echo 'Pulling Production Docker image...'
            sudo docker pull ${{ env.DOCKER_REPOSITORY }}:prod
            echo 'Stopping and removing existing container...'
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            echo 'Running new container...'
            sudo docker run -d --name myapp -p ${{ env.PROD_APP_PORT }}:${{ env.PROD_APP_PORT }} ${{ env.DOCKER_REPOSITORY }}:prod
          "
          echo "Production Docker image deployed successfully."
